/**
 * Plugins API Adapter
 * Domain-specific adapter for plugin operations
 */

import type {
  ApiResponse,
  PluginAnalysisResponse,
  PluginReinstallResponse,
  Plugin
} from '../../../shared/types/api.js';
import { API_CONFIG, buildApiBody } from '../../../config/api.js';
import type { IApiAdapter } from '../adapter.js';

/**
 * Plugins API Adapter
 * Handles all plugin-related API operations
 */
export class PluginsApiAdapter {
  constructor(private adapter: IApiAdapter) {}

  /**
   * Analyze all plugins
   * Returns categorized list of plugins (WP.org, WPMU DEV, Custom)
   */
  async analyze(): Promise<ApiResponse<PluginAnalysisResponse>> {
    const endpoint = API_CONFIG.endpoints.bootstrap;
    const body = buildApiBody('analyze_plugins');

    return this.adapter.request<PluginAnalysisResponse>(endpoint, {
      method: 'POST',
      body
    });
  }

  /**
   * Reinstall selected plugins
   * @param plugins - Array of plugin objects with slug, name, version
   * @param createBackup - Whether to create backup before reinstall
   * @param batchStart - Starting index for batch processing
   * @param batchSize - Number of plugins per batch
   * @param progressFile - Progress file name (generated by caller)
   * @param suspiciousFiles - Array of suspicious file objects to delete (selected by user)
   */
  async reinstall(
    plugins: Array<{
      slug: string;
      name?: string;
      version?: string;
      is_wpmudev?: boolean;
      wdp_id?: string | number | null;
      plugin_file?: string | null;
    }>,
    createBackup: boolean = false,
    batchStart: number = 0,
    batchSize: number = 5,
    progressFile: string = '',
    suspiciousFiles: Array<{name: string, path: string, is_directory: boolean}> = []
  ): Promise<ApiResponse<PluginReinstallResponse>> {
    const endpoint = API_CONFIG.endpoints.plugins.base;
    
    // Use provided progress file or generate new one
    const progress_file = progressFile || `plugin_reinstall_${Date.now()}.progress`;
    
    // Separate WordPress.org and WPMU DEV plugins
    const repoPlugins: Record<string, any> = {};
    const wpmuDevPlugins: Record<string, any> = {};
    
    for (const p of plugins) {
      const pluginData = { 
        name: p.name || p.slug, 
        version: p.version || 'unknown',
        slug: p.slug,
        wdp_id: p.wdp_id ?? null,
        // Main plugin basename (dir/file.php) — required for WPMU deactivate/reactivate
        plugin_file: p.plugin_file || null
      };
      
      if (p.is_wpmudev) {
        // Prefer full plugin_file as map key when available (matches original behavior)
        const key = p.plugin_file || p.slug;
        wpmuDevPlugins[key] = pluginData;
      } else {
        repoPlugins[p.slug] = pluginData;
      }
    }
    
    console.log('[ADAPTER] Sending reinstall request:', {
      repoPluginsCount: Object.keys(repoPlugins).length,
      wpmuDevPluginsCount: Object.keys(wpmuDevPlugins).length,
      suspiciousFilesCount: suspiciousFiles.length
    });
    
    const body = buildApiBody('reinstall_plugins', {
      repo_plugins: repoPlugins, // WordPress.org plugins
      wpmu_dev_plugins: wpmuDevPlugins, // WPMU DEV plugins
      suspicious_files: suspiciousFiles, // Selected suspicious files to delete
      progress_file: progress_file,
      batch_start: batchStart,
      batch_size: batchSize,
      create_backup: createBackup ? '1' : '0'
    });

    return this.adapter.request<PluginReinstallResponse>(endpoint, {
      method: 'POST',
      body
    });
  }

  /**
   * Poll for reinstall progress updates
   * @param progressFile - Progress file to poll
   * @param onProgress - Progress callback
   * @returns Cancel function
   */
  pollReinstallProgress(
    progressFile: string,
    onProgress: (progress: any) => void,
    interval: number = API_CONFIG.polling.interval
  ): () => void {
    return this.adapter.pollProgress(progressFile, onProgress, interval);
  }

  /**
   * Create a backup of all plugins
   */
  async createBackup(): Promise<ApiResponse<{ backup_path: string }>> {
    const endpoint = API_CONFIG.endpoints.plugins.base;
    const body = buildApiBody('create_plugin_backup');

    return this.adapter.request(endpoint, {
      method: 'POST',
      body
    });
  }

  /**
   * Get selected plugins data
   * @param allPlugins - All plugin categories
   * @param selectedWpOrg - Selected WP.org plugin slugs
   * @param selectedWpmuDev - Selected WPMU DEV plugin slugs
   */
  getSelectedPlugins(
    allPlugins: PluginAnalysisResponse['results'],
    selectedWpOrg: string[],
    selectedWpmuDev: string[]
  ): Plugin[] {
    const wpOrgSelected = (allPlugins.wp_org_plugins || []).filter(
      (p) => selectedWpOrg.includes(p.slug)
    );
    const wpmuDevSelected = (allPlugins.wpmu_dev_plugins || []).filter(
      (p) => selectedWpmuDev.includes(p.slug)
    );

    return [...wpOrgSelected, ...wpmuDevSelected];
  }
}
