/**
 * Themes API Adapter
 * Domain-specific adapter for theme operations
 */

import type {
  ApiResponse,
  ThemeAnalysisResponse
} from '../../../shared/types/api.js';
import { API_CONFIG, buildApiBody } from '../../../config/api.js';
import type { IApiAdapter } from '../adapter.js';

/**
 * Themes API Adapter
 * Handles all theme-related API operations
 */
export class ThemesApiAdapter {
  constructor(private adapter: IApiAdapter) {}

  /**
   * Analyze all themes
   * Returns categorized list of themes (WP.org, Custom, Suspicious)
   */
  async analyze(): Promise<ApiResponse<ThemeAnalysisResponse>> {
    const endpoint = API_CONFIG.endpoints.themes.base;
    const body = buildApiBody('analyze_themes');

    return this.adapter.request<ThemeAnalysisResponse>(endpoint, {
      method: 'POST',
      body
    });
  }

  /**
   * Reinstall selected themes with batch processing
   * @param themes - Array of theme objects with slug, name, version
   * @param createBackup - Whether to create backup before reinstall
   * @param batchStart - Starting index for batch processing
   * @param batchSize - Number of themes per batch
   * @param progressFile - Progress file name (generated by caller)
   * @param suspiciousFiles - Array of suspicious file objects to delete (selected by user)
   */
  async reinstall(
    themes: Array<{slug: string, name?: string, version?: string}>,
    createBackup: boolean = false,
    batchStart: number = 0,
    batchSize: number = 5,
    progressFile: string = '',
    suspiciousFiles: Array<{name: string, path: string, is_directory: boolean}> = []
  ): Promise<ApiResponse<any>> {
    const endpoint = API_CONFIG.endpoints.themes.base;
    
    // Use provided progress file or generate new one
    const progress_file = progressFile || `theme_reinstall_${Date.now()}.progress`;
    
    // Convert themes array to object format for API
    const repoThemes: Record<string, any> = {};
    for (const t of themes) {
      repoThemes[t.slug] = {
        name: t.name || t.slug,
        version: t.version || 'unknown'
      };
    }
    
    console.log('[THEMES ADAPTER] Sending reinstall request:', {
      repoThemesCount: Object.keys(repoThemes).length,
      suspiciousFilesCount: suspiciousFiles.length,
      batchStart,
      batchSize
    });
    
    const body = buildApiBody('reinstall_themes', {
      repo_themes: repoThemes,
      suspicious_files: suspiciousFiles,
      progress_file: progress_file,
      batch_start: batchStart,
      batch_size: batchSize,
      create_backup: createBackup ? '1' : '0'
    });

    return this.adapter.request(endpoint, {
      method: 'POST',
      body
    });
  }

  /**
   * Poll for reinstall progress updates
   * @param progressFile - Progress file to poll
   * @param onProgress - Progress callback
   * @returns Cancel function
   */
  pollReinstallProgress(
    progressFile: string,
    onProgress: (progress: any) => void,
    interval: number = API_CONFIG.polling.interval
  ): () => void {
    return this.adapter.pollProgress(progressFile, onProgress, interval);
  }

  /**
   * Create a backup of all themes
   */
  async createBackup(): Promise<ApiResponse<{ backup_path: string }>> {
    const endpoint = API_CONFIG.endpoints.themes.base;
    const body = buildApiBody('create_theme_backup');

    return this.adapter.request(endpoint, {
      method: 'POST',
      body
    });
  }
}
