<?php
/**
 * Clean Sweep — embedded keys for offline signature packs (csig-v1).
 *
 * Generated by signatures/build/generate_keys.php --write-embedded
 * Private signing key is NOT embedded (see keys/private/sign.pem).
 */

if (!class_exists('CleanSweep_SignatureEmbeddedKeys')) {

class CleanSweep_SignatureEmbeddedKeys {

    const ENC_KEY_B64 = 'n5PnJa1CLrGWeIKjTOKpQQqUj3QNXILIC9c+GM+AzUo=';

    const PUBLIC_KEY_PEM = <<<'PEM'
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEnAbpip6T9w+tfxYRR1rdqzo9rNRP
FeeQk9uZwXqIni45Kj7JX2KwSIw1vZkL5v+bWz4v2cJuKnL8xrNczCLB3A==
-----END PUBLIC KEY-----
PEM;

    public static function encryption_key_bin() {
        $raw = base64_decode(self::ENC_KEY_B64, true);
        if ($raw === false || strlen($raw) !== 32) {
            return '';
        }
        return $raw;
    }

    public static function public_key_pem() {
        return trim(self::PUBLIC_KEY_PEM) . "\n";
    }

    public static function is_configured() {
        return self::encryption_key_bin() !== ''
            && strpos(self::PUBLIC_KEY_PEM, 'REPLACE_ME') === false;
    }
}

} // class_exists
